import csv
import io
import logging
from pathlib import Path

from fpdf import FPDF

logger = logging.getLogger(__name__)

_SEVERITY_COLORS = {
    "Critical": (192, 57,  43),
    "Serious":  (230, 126, 34),
    "Moderate": (41,  128, 185),
    "Minor":    (39,  174, 96),
}

_ARIAL_VARIANTS = {
    "":  "/System/Library/Fonts/Supplemental/Arial.ttf",
    "B": "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
    "I": "/System/Library/Fonts/Supplemental/Arial Italic.ttf",
    "BI":"/System/Library/Fonts/Supplemental/Arial Bold Italic.ttf",
}
_FONT_NAME = "Arial"


def _register_font(pdf: FPDF) -> str:
    """Register Arial TTF variants if available, return font name to use."""
    if all(Path(p).exists() for p in _ARIAL_VARIANTS.values()):
        for style, path in _ARIAL_VARIANTS.items():
            pdf.add_font(_FONT_NAME, style=style, fname=path)
        return _FONT_NAME
    return "Helvetica"


def _clean(text: str, limit: int = 200) -> str:
    """Replace characters outside Latin-1 with ASCII equivalents as a safety net."""
    if not text:
        return ""
    replacements = {
        "—": "-", "–": "-", "‒": "-",
        "‘": "'", "’": "'",
        "“": '"', "”": '"',
        "…": "...", "×": "x",
        "•": "*", "✓": "ok", "✕": "x",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    # Drop anything still outside Latin-1
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text[:limit]


class _Report(FPDF):
    def __init__(self, scan_target: str, scanned_at: str, font: str):
        super().__init__()
        self._scan_target = scan_target
        self._scanned_at = scanned_at
        self._font = font

    def header(self):
        self.set_fill_color(27, 58, 107)
        self.rect(0, 0, 210, 18, "F")
        self.set_font(self._font, "B", 11)
        self.set_text_color(255, 255, 255)
        self.set_xy(8, 4)
        self.cell(0, 5, "Section 508 / WCAG 2.1 AA Scan Report", ln=True)
        self.set_font(self._font, "", 7)
        self.set_xy(8, 10)
        self.cell(0, 4, _clean(f"Target: {self._scan_target[:100]}   |   {self._scanned_at}", 200))
        self.set_text_color(0, 0, 0)
        self.ln(12)

    def footer(self):
        self.set_y(-12)
        self.set_font(self._font, "", 7)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, f"Generated by 508 Scanner  |  Page {self.page_no()}/{{nb}}", align="C")
        self.set_text_color(0, 0, 0)


def _severity_badge(pdf: _Report, sev: str, x: float, y: float) -> None:
    r, g, b = _SEVERITY_COLORS.get(sev, (100, 100, 100))
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(pdf._font, "B", 7)
    pdf.set_xy(x, y)
    pdf.cell(22, 5, sev, fill=True, align="C")
    pdf.set_text_color(0, 0, 0)


def export_pdf(report: dict, output_path: str) -> str:
    findings = report.get("findings", [])
    summary  = report.get("summary", {})
    target   = report.get("scan_target", "")
    scanned  = report.get("scanned_at", "")
    deduped  = report.get("deduped_count", 0)

    pdf = _Report(scan_target=_clean(target, 120), scanned_at=_clean(scanned, 40), font="")
    font = _register_font(pdf)
    pdf._font = font  # set after registration

    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Executive Summary ─────────────────────────────────────────────────────
    pdf.set_font(font, "B", 13)
    pdf.cell(0, 7, "Executive Summary", ln=True)
    pdf.set_draw_color(27, 58, 107)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    card_w, card_h = 42, 22
    for i, sev in enumerate(["Critical", "Serious", "Moderate", "Minor"]):
        x = 10 + i * (card_w + 3)
        y = pdf.get_y()
        r, g, b = _SEVERITY_COLORS[sev]
        pdf.set_fill_color(r, g, b)
        pdf.rect(x, y, card_w, card_h, "F")
        pdf.set_text_color(255, 255, 255)
        pdf.set_font(font, "B", 16)
        pdf.set_xy(x, y + 2)
        pdf.cell(card_w, 8, str(summary.get(sev, 0)), align="C")
        pdf.set_font(font, "", 7)
        pdf.set_xy(x, y + 11)
        pdf.cell(card_w, 5, sev.upper(), align="C")
        pdf.set_text_color(0, 0, 0)

    pdf.ln(card_h + 5)
    pdf.set_font(font, "", 8)
    note = f"Total findings: {summary.get('total', 0)}."
    if deduped:
        note += f"  {deduped} duplicate(s) collapsed."
    note += "  Critical findings block assistive technology entirely - remediate first."
    pdf.multi_cell(0, 4, note)
    pdf.ln(4)

    # ── Findings Table ────────────────────────────────────────────────────────
    pdf.set_font(font, "B", 13)
    pdf.cell(0, 7, "All Findings", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    if not findings:
        pdf.set_font(font, "", 9)
        pdf.cell(0, 6, "No findings - content appears to meet WCAG 2.1 AA requirements.", ln=True)
    else:
        col_w = [24, 80, 50, 18, 18]
        headers = ["Severity", "Title", "Location", "WCAG", "508"]
        pdf.set_font(font, "B", 8)
        pdf.set_fill_color(230, 230, 230)
        for i, h in enumerate(headers):
            pdf.cell(col_w[i], 6, h, border=1, fill=True)
        pdf.ln()

        pdf.set_font("Helvetica", "", 7)
        for idx, f in enumerate(findings):
            sev = f.severity.value if hasattr(f.severity, "value") else f.severity
            fill = idx % 2 == 0
            pdf.set_fill_color(250, 250, 250) if fill else pdf.set_fill_color(255, 255, 255)

            row_y = pdf.get_y()
            # Severity cell with color
            r, g, b = _SEVERITY_COLORS.get(sev, (100, 100, 100))
            pdf.set_fill_color(r, g, b)
            pdf.set_text_color(255, 255, 255)
            pdf.set_font(font, "B", 7)
            pdf.cell(col_w[0], 5, _clean(sev, 12), border=1, fill=True, align="C")
            pdf.set_text_color(0, 0, 0)
            pdf.set_font(font, "", 7)
            pdf.set_fill_color(250, 250, 250) if fill else pdf.set_fill_color(255, 255, 255)

            pdf.cell(col_w[1], 5, _clean(f.title, 55), border=1, fill=fill)
            pdf.cell(col_w[2], 5, _clean(f.location, 38), border=1, fill=fill)
            pdf.cell(col_w[3], 5, _clean(f.wcag_sc, 8), border=1, fill=fill, align="C")
            pdf.cell(col_w[4], 5, _clean(f.sec508_ref, 8), border=1, fill=fill, align="C")
            pdf.ln()

    # ── Detail Blocks (Critical + Serious) ───────────────────────────────────
    priority = [f for f in findings
                if (f.severity.value if hasattr(f.severity, "value") else f.severity)
                in ("Critical", "Serious")]
    if priority:
        pdf.add_page()
        pdf.set_font(font, "B", 13)
        pdf.cell(0, 7, "Critical & Serious - Detail", ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

        for f in priority:
            sev = f.severity.value if hasattr(f.severity, "value") else f.severity
            r, g, b = _SEVERITY_COLORS.get(sev, (100, 100, 100))
            pdf.set_draw_color(r, g, b)
            pdf.set_line_width(1)

            block_y = pdf.get_y()

            # Title row
            _severity_badge(pdf, sev, 10, block_y)
            pdf.set_xy(35, block_y)
            pdf.set_font(font, "B", 9)
            pdf.cell(0, 5, _clean(f.title, 90), ln=True)
            pdf.ln(1)

            # Meta row
            pdf.set_font(font, "", 7.5)
            pdf.set_x(10)
            pdf.cell(30, 4, f"Rule: {_clean(f.rule, 30)}")
            pdf.cell(35, 4, f"WCAG: {_clean(f.wcag_sc, 15)}")
            pdf.cell(35, 4, f"508: {_clean(f.sec508_ref, 12)}")
            pdf.ln(5)

            pdf.set_x(10)
            pdf.cell(22, 4, "Location:")
            pdf.set_font(font, "", 7.5)
            pdf.multi_cell(0, 4, _clean(f.location, 100))

            pdf.set_font(font, "", 7.5)
            pdf.set_x(10)
            pdf.cell(22, 4, "Description:")
            pdf.multi_cell(0, 4, _clean(f.description, 300))

            if f.snippet:
                pdf.set_font(font, "", 7)
                pdf.set_fill_color(245, 245, 245)
                pdf.set_x(10)
                pdf.multi_cell(0, 4, _clean(f.snippet, 120), fill=True)

            if f.suggested_fix:
                pdf.set_font(font, "B", 7.5)
                pdf.set_fill_color(234, 246, 234)
                pdf.set_x(10)
                pdf.multi_cell(0, 4, f"Fix: {_clean(f.suggested_fix, 200)}", fill=True)

            # Left accent bar
            end_y = pdf.get_y()
            pdf.set_draw_color(r, g, b)
            pdf.set_line_width(1.5)
            pdf.line(9, block_y, 9, end_y)
            pdf.set_line_width(0.2)
            pdf.set_draw_color(200, 200, 200)

            pdf.ln(4)

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(output))
    logger.info("PDF report written to %s", output)
    return str(output)


def export_csv(report: dict) -> str:
    fields = ["id", "severity", "rule", "wcag_sc", "sec508_ref", "title", "location", "source", "suggested_fix"]
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=fields, extrasaction="ignore")
    writer.writeheader()
    for f in report.get("findings", []):
        row = f.model_dump() if hasattr(f, "model_dump") else dict(f)
        row["severity"] = row["severity"].value if hasattr(row["severity"], "value") else row["severity"]
        writer.writerow({k: row.get(k, "") for k in fields})
    return buf.getvalue()
